### ISSUE TITLE
Adicionar descrição da importância da criticidade ou funcionamento da criticidade no documento do modelo de severidade e prioridade

### ISSUE THREAD

**Issue by JerffersonJunior** [EngSoft-UFMS/documentation#1]
É importante para a didática do usuário entender o funcionamento da criticidade e a forma como a mesma foi moldada. Apesar do modelo apresentar disposta de forma simples, falta uma breve explicação acerca de sua origem. No arquivo "severity_and_priority_model.md" deve-se adicionar tal explicação através de uma breve adição em seu conteúdo.

**Comment by LourdesOshiroIgarashi** [comment]
Adicionei uma explicação sobre a criticidade e como as issues são ordenadas a partir da criticidade
