### ISSUE TITLE
Adicionar Modelo de Ramificação/Branching Model

### ISSUE THREAD

**Issue by JerffersonJunior** [EngSoft-UFMS/documentation#2]
Para o desenvolvimento do trabalho é extremamente importante escolher o modelo de ramificação adequado para o nosso time, visto que o seu andamento depende dessa escolha. Sem o branching model se torna inviável a progressão do projeto, visto que a indecisão e a desorganização podem causar sérios problemas conforme o trabalho conjunto avança. Para isso, peço para que @oliveiraeverton e @wagnerUFMS especifiquem o mais urgentemente possível o modelo a ser trabalhado pelo time.

**Comment by LourdesOshiroIgarashi** [comment]
Pesquisei alguns modelos de ramificação e esses foram os que melhor se encaixaram para nossa necessidade do trabalho:

1. Modelo Git Flow:

- Branch principal: main ou master
- Branch de desenvolvimento: develop
- Branches de recursos: feature/{nome-da-feature}
- Branches de lançamento: release/{versão}
- Branches de correção de bugs: bugfix/{nome-do-bug}
- Branches de hotfix: hotfix/{nome-do-bug}
- Branches de suporte: support/{nome-da-branch-de-suporte}

O Git Flow é um modelo popular que define diferentes tipos de branches para cada etapa do ciclo de vida do desenvolvimento de software. Ele oferece uma estrutura clara para o desenvolvimento de recursos, correção de bugs, lançamento de versões e suporte a longo prazo.

2. Modelo GitHub Flow:

- Branch principal: main ou master
- Branches de recursos: feature/{nome-da-feature}

O GitHub Flow é um modelo simplificado que enfatiza a implantação contínua. Todo o trabalho é feito em branches de recursos, e as alterações são mescladas no branch principal assim que estiverem prontas. É um modelo adequado para equipes menores e fluxos de trabalho mais ágeis.

3. Modelo OneFlow:

- Branch principal: main ou master
- Branch de desenvolvimento: develop
- Branches de recursos: feature/{nome-da-feature}

O OneFlow é um modelo simplificado baseado no Git Flow, mas com menos branches. Ele mantém um branch de desenvolvimento para integração contínua de recursos e uma branch principal estável para produção.

4. Modelo Trunk-Based Development:

- Branch principal: main ou master

O Trunk-Based Development é um modelo altamente simplificado que incentiva o desenvolvimento direto no branch principal. As alterações são enviadas por meio de revisões de código e testes automatizados para garantir a qualidade do código. Esse modelo é mais adequado para equipes pequenas que trabalham em projetos menores e com implantações frequentes.

**Comment by oliveiraeverton** [comment]
feito!

**Comment by LourdesOshiroIgarashi** [comment]
É necessário explicar porque o modelo Github Flow foi escolhido, as tomadas de decisão que levaram a escolha do modelo de ramificação, além disso é usado o termo URI na explicação dos exemplos e o termo correto é Beecrowd.

**Comment by JerffersonJunior** [comment]
Também seria interessante que o modelo seguisse a subseção prescritas pela tomada de decisão, dentro do nosso modelo de prioridade e severidade.

**Comment by oliveiraeverton** [comment]
Foi escolhido esse modelo de ramificação porque qualquer coisa na ramificação principal pode ser implantada ou melhorada.
É mais fácil comprometer-se com uma ramificação localmente e enviar o trabalho para a mesma ramificação do remoto.
Possibilidade de abrir uma Pull Request para revisão e ajuda.
