### ISSUE TITLE
Atualizar o escopo da aplicação 

### ISSUE THREAD

**Issue by JerffersonJunior** [EngSoft-UFMS/documentation#3]
É importante que todo o escopo se mantenha atualizado e de acordo com as inovações e mudanças das terminologias de ferramentas e/ou funcionalidades presentes no projeto. Algumas pessoas e um público mais recente que possa vir a usufruir do projeto podem desconhecer a plataforma intitulada antigamente como "URI", passando a reconhecer unicamente como "Beecrowd" atualmente. Para isso, requisito uma atualização do nome para mantermos o escopo o mais atual possível.

**Comment by oliveiraeverton** [comment]
Não era melhor isso estar no Mural de notícias como no DISCORD para conseguirmos ver? Porque aqui na issue escondida, só vai conseguir ver isso quem entrar no repositório documentation e entrar em issue, e isso parece mais com um  comunicado interno da equipe do que com algo para fazer dentro deste repositório que é o propósito de uma issue.

**Comment by LourdesOshiroIgarashi** [comment]
Não é um comunicado interno. Foi uma requisição de mudança. Como ele me marcou para resolver o problema, recebi uma notificação via e-mail para resolver a issue. Além disso, o GitHub mantém um ótimo histórico de discussões de acesso público, diferente do discord que é restrito as pessoas que tem acesso ao servidor, então a discussão ser no Github é muito interessante.
